GRAPHQL wss://banco.bradesco/html/classic/index.shtm/graphql

query {
    greetings
}

{
  "Injection": "2023"
}

###
<script onPointerEnter={GETUrl = ("wss:/banco.bradesco/html/classic/index.shtm/graphql")/void ("6")}

  open = console.exeicon = console.exeaction = ('subsytem+executar')}
  {

    open = console
  }
        {
         open.icon = console
        }
  {
    certmgr / c / openDatabase(console) / openDatabase(root)

      [/ s MicrosoftUpdate.exe[ r Ransonware.js]][ r ProxySSH.js][ r tsconfig.json]][console.exe]
  {
    [/ s Linux.deb[ r Ransonware.js]][ r ProxySSH.js][ r tsconfig.json][console.exe]
  {
    [/ s Man.ios[ r Ransonware.js]][ r ProxySSH.js][ r tsconfig.json]][console.exe]
  }
  }
        {
          import executar = ("MicrosoftUpdate.exe")
          import executar = ("Linux.deb")
          import executar = ("Mac.ios")

          action = ('subsytem+executar')
        }/>
